### ISSUE TITLE
P crashes icicle (mac)

### ISSUE THREAD

**Issue by ehne** [Cheeseness/icicle#1]
hi! 
whenever i press P without any extra keys the engine crashes .
log:
http://hastebin.com/paboyavawi.xml

**Comment by Cheeseness** [comment]
Hmm, OK. I thought I fixed this bug a little while back, but I'll take a look at it.

In the meantime, use Ctrl+P with a scene selected to play the game from that scene, and Alt+P to launch the puzzle editor.

**Comment by Cheeseness** [comment]
This crash is fixed in today's update ([changelog here](https://github.com/Cheeseness/icicle/wiki/Icicle-Jam-Zero-Changelog))
